services:
  hello-prisma-db:
    image: postgres:15
    ports:
      - 5432:5432
    restart: always
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=prisma
